---
title: "Lab 06b - Simpson's paradox"
author: "Insert your name here"
date: "Insert date here"
output: github_document
---

### Load packages and data

```{r load-packages, message = FALSE}
library(tidyverse) 
library(mosaicData) 
```

### Exercise 1

```{r}

data(Whickham)
?Whickham
```
### Exercise 2
```{r}

  
Whickham%>%
  ggplot(aes(x=outcome, fill=smoker)) +
  geom_bar( position="dodge")

Whickham%>%
  ggplot(aes(x=smoker, y=prob, fill=outcome)) +
  geom_bar(stat="identity", position="dodge")


## This graph does not give any explanations on possibilities. 
## it only depicts the numbers. 
## So I tried ratio-manner approaches. 

 Whickham %>%
  count(smoker, outcome) %>%
  group_by(outcome) %>%
  dplyr::mutate(prob = n/sum(n))%>%
  ggplot(aes(x=outcome, y=prob, fill=smoker)) +
  geom_bar(stat="identity")


```
### Exercise 3
```{r}

Whickham <-Whickham %>%
  mutate(age_cat=case_when(
    age <= 44 ~ "18-44",
    age > 44 & age <= 64 ~ "45-64",
    age > 64 ~ "65+",
    TRUE ~ NA_character_))

Whickham %>%
  count(smoker, age_cat, outcome)%>%
  group_by(outcome) %>%
  dplyr::mutate(prob = n/sum(n))%>%
  ggplot(aes(x=outcome, y=prob, fill=smoker)) +
  facet_grid(~age_cat)+
  geom_bar(stat="identity")


  
  

```